"use strict";
var express = require("express");
var cors = require("cors");
var app = express();
var PORT = process.env.PORT || 4000;
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
var HomeRoute = require("./routes/HomeRoute/HomeRoute");
var UserRoute = require("./routes/UserRoute/UserRoute");
app.use("/", HomeRoute);
app.use("/", UserRoute);
app.listen(PORT, function () { return console.log("Server running on port " + PORT); });
